#!/usr/bin/env python3
"""
gen_card_names.py — Generate internal/gamestate/cardnames.go from HearthstoneJSON.

Fetches the full card database, filters for Battlegrounds-relevant cards
(BG heroes and BG minions), and writes a Go source file with a CardName()
lookup function.

Usage:
    .claude/skills/gen-card-names/gen_card_names.py [--out PATH] [--dry-run]

Flags:
    --out PATH    Output Go file (default: internal/gamestate/cardnames.go)
    --dry-run     Print the generated file without writing it
    --force       Skip cache and re-fetch from HearthstoneJSON
"""

import argparse
import json
import re
import sys
import time
import urllib.request
from pathlib import Path

API_URL = "https://api.hearthstonejson.com/v1/latest/enUS/cards.json"
CACHE_FILE = Path(__file__).parent / "cards_cache.json"
CACHE_MAX_AGE = 7 * 24 * 3600  # 7 days

# BG set names as they appear in the API
BG_SETS = {
    "BATTLEGROUNDS",
    "BG25", "BG26", "BG27", "BG28", "BG29", "BG30",
    "BG31", "BG32", "BG33", "BG34", "BG35", "BG36",
    "BGDUO",
    "VANILLA",  # includes some classic BG heroes
}

# Card types to include
INCLUDE_TYPES = {"HERO", "MINION"}

# Card IDs to explicitly include even if not in a BG set
# (e.g. TB_ prefixed placeholder heroes appear in logs)
EXPLICIT_INCLUDES_RE = re.compile(r"^TB_BaconShop_")

# Card IDs to explicitly exclude (internal placeholders, test cards, etc.)
EXPLICIT_EXCLUDES_RE = re.compile(r"_HERO_PH$|Debug|Tutorial|test_", re.IGNORECASE)


def fetch_cards(force: bool) -> list[dict]:
    """Return card list from cache or remote."""
    if not force and CACHE_FILE.exists():
        age = time.time() - CACHE_FILE.stat().st_mtime
        if age < CACHE_MAX_AGE:
            print(f"  Using cached cards ({int(age/3600)}h old)", file=sys.stderr)
            with open(CACHE_FILE) as f:
                return json.load(f)

    print("  Fetching cards from HearthstoneJSON...", file=sys.stderr)
    req = urllib.request.Request(API_URL, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = resp.read()
    cards = json.loads(data)
    CACHE_FILE.parent.mkdir(exist_ok=True)
    with open(CACHE_FILE, "wb") as f:
        f.write(data)
    print(f"  Fetched {len(cards)} cards, cached to {CACHE_FILE}", file=sys.stderr)
    return cards


def is_bg_relevant(card: dict) -> bool:
    """Return True if this card should appear in the name map."""
    cid = card.get("id", "")
    ctype = card.get("type", "")
    cset = card.get("set", "")

    if ctype not in INCLUDE_TYPES:
        return False
    if EXPLICIT_EXCLUDES_RE.search(cid):
        return False
    if EXPLICIT_INCLUDES_RE.match(cid):
        return True
    if cset not in BG_SETS:
        return False
    # Must be BG-tagged or a hero
    is_bg = (
        card.get("battlegroundsHero")
        or card.get("battlegroundsNormalDbfId")
        or card.get("battlegroundsPremiumDbfId")
        or ctype == "HERO" and "BG" in cid
        or ctype == "MINION" and cset in BG_SETS
    )
    return bool(is_bg)


def go_string(s: str) -> str:
    """Escape a string for Go source."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def generate_go(entries: list[tuple[str, str]], package: str = "gamestate") -> str:
    """Generate the Go source file content."""
    lines = [
        "// Code generated by gen_card_names.py — DO NOT EDIT.",
        "// Run: .claude/skills/gen-card-names/gen_card_names.py",
        f"// Source: {API_URL}",
        "",
        f"package {package}",
        "",
        "// cardNames maps Hearthstone card IDs to their display names.",
        "// Covers Battlegrounds heroes and minions.",
        "var cardNames = map[string]string{",
    ]
    for cid, name in sorted(entries):
        lines.append(f'\t"{go_string(cid)}": "{go_string(name)}",')
    lines.append("}")
    lines.append("")
    lines.append("// CardName returns the display name for a card ID,")
    lines.append("// or the card ID itself if not found.")
    lines.append("func CardName(cardID string) string {")
    lines.append("\tif name, ok := cardNames[cardID]; ok {")
    lines.append("\t\treturn name")
    lines.append("\t}")
    lines.append("\treturn cardID")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="internal/gamestate/cardnames.go",
                        help="Output Go file path")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print output without writing")
    parser.add_argument("--force", action="store_true",
                        help="Bypass cache, re-fetch from HearthstoneJSON")
    args = parser.parse_args()

    cards = fetch_cards(args.force)

    entries = []
    for card in cards:
        if is_bg_relevant(card):
            cid = card["id"]
            name = card.get("name", "")
            if name:
                entries.append((cid, name))

    print(f"  {len(entries)} BG-relevant cards selected", file=sys.stderr)

    go_src = generate_go(entries)

    if args.dry_run:
        print(go_src)
        return

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(go_src)
    print(f"  Written: {out} ({len(entries)} entries)")


if __name__ == "__main__":
    main()
